# Generated by Django 4.1.1 on 2022-09-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='del_price',
            field=models.IntegerField(default=0),
        ),
    ]
