# Generated by Django 4.1.1 on 2022-09-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='del_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Id',
            field=models.IntegerField(default=0),
        ),
    ]
