# Generated by Django 4.1.1 on 2022-09-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_del_price_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductGallery',
        ),
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
